export enum ATTRIBUTES {
  CON = 'CONSTITUTION',
  DEX = 'DEXTERITY',
  INT = 'INTELLECT',
  MIG = 'MIGHT',
  PER = 'PERCEPTION',
  RES = 'RESOLVE',
}

export const ATTRIBUTE_MAX_CREATION_VALUE = 18
export const ATTRIBUTE_MIN_CREATION_VALUE = 3
